name: Sync from GitLab

on:
  repository_dispatch:
    types: [sync]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Sync from GitLab to GitHub
        env:
          GITLAB_TOKEN: ${{ secrets.glpat-BeU4hi4BfinQy7qbC3xD }}
          GITLAB_REPO_URL: ${{ secrets.https://gitlab.com/rahul3260235/CodeMove.git }}
          GITHUB_TOKEN: ${{ secrets.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 }}
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clone the GitLab repository
          git clone https://${glpat-BeU4hi4BfinQy7qbC3xD}@${https://gitlab.com/rahul3260235/CodeMove.git} gitlab-repo
          cd gitlab-repo

          # Add the GitHub repository as a remote
          git remote add github https://x-access-token:${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}@github.com/${{ https://github.com/DXLink/GitHub_ActionsWorkflow.git  }}.git

          # Push changes from GitLab to GitHub
          git push github --mirror
